# Generated by Django 3.0.3 on 2020-02-24 09:40

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('img', models.ImageField(upload_to='ana_img', verbose_name='微语配图')),
                ('like_num', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('comment_num', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('body', DjangoUeditor.models.UEditorField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('img', models.ImageField(upload_to='article_img', verbose_name='文章配图')),
                ('page_view', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('body', DjangoUeditor.models.UEditorField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='lev_mes_img', verbose_name='留言配图')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photo_img', verbose_name='相册')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_site', models.CharField(max_length=15, verbose_name='创建地点')),
                ('desc', models.CharField(max_length=50, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='SelfIntroduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='年龄')),
                ('profession', models.CharField(max_length=30, verbose_name='职业')),
                ('hobby', models.CharField(max_length=100, verbose_name='爱好')),
                ('img', models.ImageField(upload_to='personage_img', verbose_name='头像')),
                ('per_skill_img', models.ImageField(upload_to='per_skill_img', verbose_name='技能图谱')),
                ('per_skillful', models.FloatField(default=0.8, verbose_name='技能熟练')),
                ('wechat_num', models.CharField(default='hzf19960922', max_length=20, verbose_name='微信')),
                ('wechat_img', models.ImageField(upload_to='wechat_img', verbose_name='微信二维码')),
                ('qq_num', models.CharField(default='1677508764', max_length=20, verbose_name='QQ')),
                ('phone', models.CharField(default='18337391053', max_length=20, verbose_name='电话')),
                ('email', models.EmailField(default='huangzhenfang2017@163.com', max_length=254, verbose_name='个人邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='ViewPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='view_page', verbose_name='页面视图')),
                ('desc', models.CharField(blank=True, max_length=20, null=True, verbose_name='视图描述')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='评论者')),
                ('img', models.ImageField(upload_to='comment_img', verbose_name='评论者头像')),
                ('body', models.CharField(max_length=500, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('ana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblogapp.Ana', verbose_name='微语评论')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblogapp.Article', verbose_name='文章评论')),
                ('leavemes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblogapp.LeaveMes', verbose_name='留言')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblogapp.Category', verbose_name='文章分类'),
        ),
    ]
