# Generated by Django 3.0.3 on 2020-02-25 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfintroduction',
            name='per_skill_img',
        ),
        migrations.RemoveField(
            model_name='selfintroduction',
            name='per_skillful',
        ),
        migrations.CreateModel(
            name='MySkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='技能名称')),
                ('per_skill_img', models.ImageField(upload_to='per_skill_img', verbose_name='技能图谱')),
                ('per_skillful', models.FloatField(default=0.8, verbose_name='技能熟练')),
                ('selfIntroduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblogapp.SelfIntroduction', verbose_name='个人技能')),
            ],
        ),
    ]
